### ISSUE TITLE
Make query issues more clear

### ISSUE THREAD

**Issue by quentinformatique** [belicfr/mvclite-core#1]
When you have a **query issue**, it isn't very clear : you only have the query with **no details**, you dont know what the query was.
![image](https://github.com/belicfr/mvclite-core/assets/80545291/90907bf4-05fb-42a1-a9d9-dfffde6002e6)
**You should display the full query who was sent to the database.**

**Comment by belicfr** [comment]
Given query values are now displayed as "With values: …" line.
